### ISSUE TITLE
Claiming namespace [phoenisx]

### ISSUE THREAD

**Issue by phoenisx** [EclipseFdn/open-vsx.org#1160]
Extension on open-vsx store: https://open-vsx.org/extension/phoenisx/cssvar
Extension on Microsoft marketplace: https://marketplace.visualstudio.com/items?itemName=phoenisx.cssvar

**Comment by kineticsquid** [comment]
@phoenisx, I can see that this extension is currently auto-published. Can you submit a PR to https://github.com/open-vsx/publish-extensions/blob/master/extensions.json to have this stopped. When that is merged, I'll assign namespace ownership. Thanks

**Comment by filiptronicek** [comment]
No need anymore, I just pushed a commit removing the extension - https://github.com/open-vsx/publish-extensions/commit/004854ea3045dc20e8c9d13c4c7db94a19cddab4 @kineticsquid

**Comment by phoenisx** [comment]
Thanks, @filiptronicek 🙇🏽 
I am still getting the error mentioned here: https://github.com/willofindie/vscode-cssvar/issues/35#issuecomment-1207215884


<img width="489" alt="image" src="https://user-images.githubusercontent.com/11786283/183418313-0002e9ba-1690-4a13-ab27-db20072bbcbe.png">

I guess unless I get the claim on this namespace, I won't be able to publish!! 🤔

**Comment by kineticsquid** [comment]
@phoenisx You're good now!
