### ISSUE TITLE
Remove Thunder Client up to v2.30.0

### ISSUE THREAD

**Issue by rangav** [EclipseFdn/open-vsx.org#3171]
Hi

I am the owner of the extension [Thunder Client](https://open-vsx.org/extension/rangav/vscode-thunder-client)

Could you please delete all versions up to and including **v2.30.0**?

These versions are no longer supported, and we would like them to be removed.

**Extension Name**: [Thunder Client](https://open-vsx.org/extension/rangav/vscode-thunder-client)
**Older Versions to be Deleted**: All versions up to v2.30.0
**Reason:** Legal and business requirements.

Thanks
Ranga

**Comment by kineticsquid** [comment]
Done!

**Comment by rangav** [comment]
Thank you @kineticsquid 

The **2.30.0** version is still showing in the list. Can you please remove this version also?

<img width="317" alt="Screenshot 2024-12-02 at 15 41 00" src="https://github.com/user-attachments/assets/bd5005bb-f8b5-49dd-8308-d36b37ede8d2">

**Comment by rangav** [comment]
Thank you @kineticsquid, for your support.

**Comment by kineticsquid** [comment]
Oops, should have clarified. The one sentence said 'up to and including', the second said 'up to'. 2.30.0 is now deleted.

**Comment by rangav** [comment]
Thank you
