### ISSUE TITLE
Claiming namespace [HuaweiCloud]

### ISSUE THREAD

**Issue by HUAWEICLOUD-DEVELOPER** [EclipseFdn/open-vsx.org#6344]
I'd like to become the owner of the namespace HuaweiCloud. I am a maintainer of Huawei Developer Space extensions published on open-vsx.org.

I have released the Huawei Developer Space extension to the Visual Studio Code marketplace at the following address: https://marketplace.visualstudio.com/items?itemName=HuaweiCloud.developerspace

By the way, could you please tell me the reason this issue was rejected? I would like to know how to fix it.
<img width="1303" height="660" alt="Image" src="https://github.com/user-attachments/assets/8f21ddb0-6f6b-4fe5-bb12-13ffa9c9b685" />

**Comment by kineticsquid** [comment]
I'm sorry, this is insufficient. I need you to document a connection between this GitHub ID `HuaweiCloud-Developer` and that extension. 
- make the repo public
- give me temporary access so I can verify
- provide screen cap(s) that show this ID has write access to the repo
- if you own the domain name, you can add a TXT record, e.g. with a URL to this issue.

**Comment by kineticsquid** [comment]
@HuaweiCloud-Developer ^^^^

**Comment by HuaweiCloud-Developer** [comment]
Sorry, due to company requirements, we cannot disclose the plugin code. However, we can provide images to prove that we are the owners of the plugin.
Currently, we have also published the plugin on the Visual Studio Code platform, which can also serve as proof of our ownership: https://marketplace.visualstudio.com/items?itemName=HuaweiCloud.developerspace

<img width="1226" height="1312" alt="Image" src="https://github.com/user-attachments/assets/226833ce-6cfc-44c6-a9eb-7fb014306ddd" />
Will we be able to pass the review?

**Comment by kineticsquid** [comment]
Sorry, that's still not clear enough. Are you part of Huawei? If so, can you send an email from your work email (@huawei.com) to openvsx@eclipse-foundation.org?

**Comment by HuaweiCloud-Developer** [comment]
We are Huawei Cloud Computing Technologies Co., Ltd. Can we send emails using our registered email address (@huaweicloud.com)? What should be included in the email content?

**Comment by kineticsquid** [comment]
Yes, that works

**Comment by HuaweiCloud-Developer** [comment]
Okay, the email has been sent to you.
